on:
  push: 
    branches:
      - main

jobs:
  tofu:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v16
        with: 
          diagnostic-endpoint: ""
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: |
          echo "backend = \"${{ secrets.GOOGLE_BACKEND }}\"
          built = true
          region = \"${{ vars.GOOGLE_REGION }}\"
          repository_owner = \"$GITHUB_REPOSITORY_OWNER\"" > terraform.tfvars
        working-directory: amaurot

      - run: nix-shell --run "exit" shell.nix

      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}

      - name: tofu init
        run: nix-shell --run "tofu init" ../shell.nix
        working-directory: amaurot

      - name: tofu plan
        run: nix-shell --run "tofu plan" ../shell.nix
        working-directory: amaurot

      #- name: tofu apply  
      #  run: nix-shell --run "tofu apply -auto-approve" ../shell.nix
      #  working-directory: amaurot
